//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attended
    {

        public Attended()
        {
            //  this.Attended = new HashSet<Attended>();
            //  this.Attending = new HashSet<Attending>();
        }

        public Attended(decimal cuID, decimal coID, string agrade)
        {
            customer_cuId = cuID;
            course_coId = coID;
            grade = agrade;
        }

        public decimal adId { get; set; }
        public string grade { get; set; }
        public decimal course_coId { get; set; }
        public decimal customer_cuId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
