//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attending
    {

        public Attending()
        {
          //  this.Attended = new HashSet<Attended>();
          //  this.Attending = new HashSet<Attending>();
        }

        public Attending(decimal cuID, decimal coID, string cpaid)
        {
            customer_cuId = cuID;
            course_coId = coID;
            paid = cpaid;
        }

        public decimal agId { get; set; }
        public string paid { get; set; }
        public decimal course_coId { get; set; }
        public decimal customer_cuId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Course Course { get; set; }
    }
}
