//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Attended = new HashSet<Attended>();
            this.Attending = new HashSet<Attending>();
        }

        public Customer(string cpnr, string cname, string caddress, string cmail, string cphonenr)
        {
            pnr = cpnr;
            name = cname;
            address = caddress;
            mail = cmail;
            phonenr = cphonenr;
        }

        public decimal cuId { get; set; }
        public string address { get; set; }
        public string mail { get; set; }
        public string name { get; set; }
        public string phonenr { get; set; }
        public string pnr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attended> Attended { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attending> Attending { get; set; }
    }
}
