//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.entityframework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DAEF : DbContext
    {
        public DAEF()
            : base("name=DAEF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attended> Attended { get; set; }
        public virtual DbSet<Attending> Attending { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<PrerequisiteCourse> PrerequisiteCourse { get; set; }
        public virtual DbSet<FinishedStudents> FinishedStudents { get; set; }
    }
}
