//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinishedStudents
    {
        public decimal course_coId { get; set; }
        public decimal customer_cuId { get; set; }
        public string grade { get; set; }
        public System.DateTime finished_date { get; set; }
    }
}
