//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.entityframework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrerequisiteCourse
    {

        public PrerequisiteCourse()
        {

        }

        public PrerequisiteCourse(decimal dcoId, decimal dprereqCoId)
        {
            coId = dcoId;
            prereqCoId = dprereqCoId;
        }

        public decimal coId { get; set; }
        public decimal prereqCoId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Course Course1 { get; set; }
    }
}
